build:
    environment:
        php:
            version: 8.1.24
    tests:
        override:
            -
                command: ./support/init && ./support/test && ./support/coverage clover-code-coverage
                coverage:
                    file: 'sandbox/code-coverage-report/clover.xml'
                    format: 'php-clover'
    cache:
        directories:
            - sandbox/composer/
filter:
    paths:
        - source/
    excluded_paths:
        - sandbox/
        - specs/
        - support/
